project:
  type: website
  render:
    - index.qmd
    - about.qmd
    - demographics.qmd

website:
  title: "Link2Care Master Descriptive Tables"
  navbar:
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "About"
        file: about.qmd
      - text: "Demographics"
        file: demographics.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

# To make sure that R, Python, and Julia code is only executed locally, 
# configure your project to use Quarto’s freeze feature by adding this to your 
# _quarto.yml. (https://quarto.org/docs/publishing/netlify.html)
execute:
  freeze: auto